### ISSUE TITLE
Calamari segfaults

### ISSUE THREAD

**Issue by Witiko** [OCR-D/ocrd_calamari#44] opened 2020-09-22 22:38 UTC
Using the ocrd/maximum docker image from 5 days ago (2020-09-18, 9165ddaf96bc), I am receiving a segfault when running `ocrd-calamari-recognize -I OCR-D-SEG-LINE-RESEG-DEWARP -O OCR-D-OCR -p checkpoint /models/\*.ckpt.json`, where the models are those from the [model.tar.xz](https://ocr-d-repo.scc.kit.edu/models/calamari/GT4HistOCR/model.tar.xz) archive as suggested by the [OCR-D project web site](https://ocr-d.de/en/workflows#available-processors-14). Only 5 xml files are produced before the segfault, so I am assuming the issue is with the sixth image (`OCR-D-SEG-LINE-RESEG-DEWARP_f103.xml`) and its line segments. Would you like me to submit the problematic line segments for reproduction?

I noticed that a new ocrd/maximum image has been published a day later. Do you suppose the changes may affect calamari?

**Comment by kba** [comment] 2020-09-23 06:50
Thanks for the report, data to reproduce and fix this is much appreciated.

There was no update of ocrd_calamari since last week.

**Comment by Witiko** [comment] 2020-09-23 13:54
@kba For ease of reproduction, I uploaded `mets.xml`, `OCR-D-SEG-LINE-RESEG-DEWARP/` and `OCR-D-OCR/` in the state after the segfault as a ZIP archive [here](https://fi.muni.cz/~xnovot32/dump.zip). Please, let me know if you required any more information for reproduction.

**Comment by mikegerber** [comment] 2020-10-08 16:15
1. The METS file is a bit confusing, it contains in the `OCR-D-SEG-PAGE` filegroup:

* deskewed output
* denoised output                                                              
* despeckled output
* different kinds of binarization output                                                                                 
* cropped output                                                                                                        
* resegmented output                                                                                                    
* repaired output    

All in one file group. Could you provide the workflow you used to produce this?

2. Also, `mets.xml` does _not_ contain the input file group in question, so I cannot reproduce:

~~~
Input fileGrp[@USE='OCR-D-SEG-LINE-RESEG-DEWARP'] not in METS!
~~~

**Comment by Witiko** [comment] 2020-10-12 17:33
I am not able to reproduce the issue.

**Comment by mikegerber** [comment] 2020-10-13 11:19
Alright, I am closing this issue then. Please re-open and send me/upload the data if you have the same problem again!

**Closed by mikegerber** 2020-10-13 11:19 UTC
Labels: bug, question
